# Generated by Django 4.2.25 on 2025-11-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_vehiclepartrequest_table'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHasShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message related to this request-shop association', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(help_text='The vehicle part request', on_delete=django.db.models.deletion.CASCADE, related_name='request_shops', to='request.vehiclepartrequest')),
                ('shop', models.ForeignKey(help_text='The shop associated with this request', on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', to='store.shop')),
            ],
            options={
                'verbose_name': 'Request Has Shop',
                'verbose_name_plural': 'Request Has Shops',
                'db_table': 'request_has_shops',
                'ordering': ['-created_at'],
                'unique_together': {('request', 'shop')},
            },
        ),
    ]
