# Generated by Django 4.2.25 on 2025-11-02 17:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_vehiclepartrequest_table'),
        ('store', '0002_requesthasshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image', models.ImageField(blank=True, help_text='Image of the product', null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(help_text='The vehicle part request this product relates to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='request.vehiclepartrequest')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
