# Generated by Django 4.2.25 on 2025-11-08 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_create_cart_item_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the product in the cart', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
