# Generated by Django 4.2.25 on 2025-11-12 17:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_quantity_to_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the recipient', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the recipient', max_length=100)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or province', max_length=100, null=True)),
                ('post_code', models.CharField(help_text='Postal or ZIP code', max_length=20)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('address1', models.CharField(help_text='Street address line 1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total amount of the order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='LKR', help_text='Currency code (ISO 4217 format, e.g., USD, LKR)', max_length=3)),
                ('reference_number', models.CharField(help_text='Unique reference number for the order', max_length=100, unique=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], help_text='Platform where the order was placed', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Current status of the order', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.ForeignKey(help_text='Shipping address for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHasItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product at the time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='LKR', help_text='Currency code (ISO 4217 format, e.g., USD, LKR)', max_length=3)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product in the order', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(help_text='The product in this order item', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_has_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='addresses_country_3b68d0_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='addresses_city_dfd875_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['post_code'], name='addresses_post_co_522c09_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference_number'], name='orders_referen_d447b0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source'], name='orders_source_b20c07_idx'),
        ),
    ]
