# Generated by Django 4.2.25 on 2025-11-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_create_order_and_address_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='The cart this order was created from (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.cart'),
        ),
    ]
