services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_HOST=vehicle-parts-db.c5m26imqm4kv.ap-southeast-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=VehicleParts123!
      - DB_NAME=vehicle_parts
      - SECRET_KEY=your-production-secret-key-here
      - ALLOWED_HOSTS=*
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
