"""
Django settings for vehicle_parts_api project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import pymysql
from pathlib import Path
from decouple import config
import os

# Load local environment file if it exists
if os.path.exists('.env.local'):
    from decouple import Config, RepositoryEnv
    config = Config(RepositoryEnv('.env.local'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1',
                       cast=lambda v: [s.strip() for s in v.split(',')])

# Production security settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'storages',  # For AWS S3 storage
    'authentication',  # Our authentication app
    'request',  # Our request app
    'store.apps.StoreConfig',  # Our store app
    'common',  # Common utilities shared across apps
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'request.middleware.FileCompressionMiddleware',  # Automatic file compression
]

ROOT_URLCONF = 'vehicle_parts_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vehicle_parts_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='vehicle_parts'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# Configure PyMySQL to work with Django
pymysql.install_as_MySQLdb()


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Note: Static and media file configuration is handled in the AWS S3 section below

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# Django REST Framework settings (moved to global exception handler section)

# JWT Settings

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Django REST Framework settings with global exception handler
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTTokenUserAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'common.utils.handle_api_exception',
    'DEFAULT_PAGINATION_CLASS': 'common.utils.CustomPageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Email Configuration
EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default='malakasanjeewa1995@gmail.com')

# AWS S3 Configuration
USE_S3 = config('USE_S3', default=False, cast=bool)

# Only enable S3 if credentials are provided
if USE_S3 and config('AWS_ACCESS_KEY_ID', default='') and config('AWS_STORAGE_BUCKET_NAME', default=''):
    # AWS S3 settings
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_VERIFY = True
    AWS_S3_USE_SSL = True
    AWS_S3_IGNORE_ACL = True
    AWS_S3_ACL = None

    # Static files (CSS, JavaScript, Images)
    # Serve static files locally for admin styles (S3 can have permission issues)
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

    # WhiteNoise configuration for serving static files
    # Use CompressedStaticFilesStorage instead of Manifest (simpler, doesn't require manifest file)
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

    # Media files (user uploads) - use S3
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
else:
    # Local storage settings (for development)
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# WhatsApp Configuration (Twilio)
TWILIO_WHATSAPP_ENABLED = config(
    'TWILIO_WHATSAPP_ENABLED', default=False, cast=bool)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
# Twilio Environment: 'sandbox' or 'production'
# Sandbox: Use for testing with Twilio WhatsApp Sandbox (limited to pre-approved numbers)
# Production: Use your approved WhatsApp Business number from Twilio
TWILIO_ENVIRONMENT = config('TWILIO_ENVIRONMENT', default='sandbox')
# WhatsApp From Number:
# Sandbox: whatsapp:+14155238886 (Twilio's sandbox number)
# Production: whatsapp:+1234567890 (Your approved WhatsApp Business number from Twilio)
TWILIO_WHATSAPP_FROM = config(
    'TWILIO_WHATSAPP_FROM', default='whatsapp:+14155238886')

# AWS CloudWatch Logs Configuration
USE_CLOUDWATCH_LOGS = config('USE_CLOUDWATCH_LOGS', default=False, cast=bool)

# Configure CloudWatch Logs if enabled and AWS credentials are available
if USE_CLOUDWATCH_LOGS and config('AWS_ACCESS_KEY_ID', default='') and config('AWS_SECRET_ACCESS_KEY', default=''):
    try:
        import watchtower
        import boto3
        
        AWS_CLOUDWATCH_LOG_GROUP = config('AWS_CLOUDWATCH_LOG_GROUP', default='vehicle-parts-api')
        AWS_CLOUDWATCH_REGION_NAME = config('AWS_CLOUDWATCH_REGION_NAME', default=config('AWS_S3_REGION_NAME', default='us-east-1'))
        
        # Create boto3 client with explicit credentials
        cloudwatch_logs_client = boto3.client(
            'logs',
            aws_access_key_id=config('AWS_ACCESS_KEY_ID', default=''),
            aws_secret_access_key=config('AWS_SECRET_ACCESS_KEY', default=''),
            region_name=AWS_CLOUDWATCH_REGION_NAME
        )
        
        # CloudWatch Logs handler
        CLOUDWATCH_HANDLER = {
            'level': 'INFO',
            'class': 'watchtower.CloudWatchLogHandler',
            'boto3_client': cloudwatch_logs_client,
            'log_group': AWS_CLOUDWATCH_LOG_GROUP,
            'stream_name': '{machine_name}-{program}-{logger_name}-{strftime:%Y-%m-%d}',
            'use_queues': True,  # Use background thread for better performance
            'create_log_group': True,  # Automatically create log group if it doesn't exist
            'filters': [],
        }
        
        CLOUDWATCH_ERROR_HANDLER = {
            'level': 'ERROR',
            'class': 'watchtower.CloudWatchLogHandler',
            'boto3_client': cloudwatch_logs_client,
            'log_group': f'{AWS_CLOUDWATCH_LOG_GROUP}-errors',
            'stream_name': '{machine_name}-{program}-{logger_name}-{strftime:%Y-%m-%d}',
            'use_queues': True,
            'create_log_group': True,
            'filters': [],
        }
        
        CLOUDWATCH_LOGGING_ENABLED = True
    except ImportError:
        CLOUDWATCH_LOGGING_ENABLED = False
        print("Warning: watchtower not installed. CloudWatch logging disabled.")
    except Exception as e:
        CLOUDWATCH_LOGGING_ENABLED = False
        print(f"Warning: Failed to configure CloudWatch logging: {str(e)}")
else:
    CLOUDWATCH_LOGGING_ENABLED = False

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"time": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "module": "%(module)s", "pathname": "%(pathname)s", "lineno": %(lineno)d}',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'common': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Add CloudWatch handlers if enabled
if CLOUDWATCH_LOGGING_ENABLED:
    LOGGING['handlers']['cloudwatch'] = CLOUDWATCH_HANDLER
    LOGGING['handlers']['cloudwatch_errors'] = CLOUDWATCH_ERROR_HANDLER
    
    # Add CloudWatch to all loggers
    for logger_name in LOGGING['loggers']:
        if 'cloudwatch' not in LOGGING['loggers'][logger_name]['handlers']:
            LOGGING['loggers'][logger_name]['handlers'].append('cloudwatch')
    
    # Add CloudWatch errors handler to error loggers
    if 'django.request' in LOGGING['loggers']:
        LOGGING['loggers']['django.request']['handlers'].append('cloudwatch_errors')
    
    # Root logger also gets CloudWatch
    LOGGING['root']['handlers'].append('cloudwatch')
