# Generated by Django 4.2.25 on 2025-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_otp_attempts_user_otp_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[],  # Validators are handled at the model level
                help_text="Sri Lankan phone number used for login (E.164 format: +94771234567 or local: 0771234567)"
            ),
        ),
    ]

