# Generated by Django 4.2.25 on 2025-12-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_phone_not_null'),
    ]

    operations = [
        migrations.RunSQL(
            # Set NOT NULL constraint on phone column
            sql="ALTER TABLE users MODIFY COLUMN phone VARCHAR(15) NOT NULL;",
            reverse_sql="ALTER TABLE users MODIFY COLUMN phone VARCHAR(15) NULL;",
        ),
    ]

