# Generated by Django 5.2.7 on 2025-10-25 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('van', 'Van'), ('suv', 'SUV'), ('other', 'Other')], help_text='Type of vehicle', max_length=20)),
                ('vehicle_model', models.CharField(help_text='Model of the vehicle (e.g., Toyota Camry, Honda Civic)', max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(help_text='Year of the vehicle')),
                ('part_name', models.CharField(help_text='Name of the part being requested', max_length=200)),
                ('part_number', models.CharField(blank=True, help_text='Part number if available', max_length=100, null=True)),
                ('vehicle_image', models.ImageField(blank=True, help_text='Image of the vehicle', null=True, upload_to='vehicle_images/')),
                ('part_image', models.ImageField(blank=True, help_text='Image of the part', null=True, upload_to='part_images/')),
                ('part_video', models.FileField(blank=True, help_text='Video of the part', null=True, upload_to='part_videos/')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_part_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Part Request',
                'verbose_name_plural': 'Vehicle Part Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
