# Generated by Django 4.2.25 on 2025-11-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiclepartrequest',
            table='vehicle_part_requests',
        ),
    ]
